<?php

namespace Database\Seeders;

use App\Models\Amenity;
use App\Models\Category;
use App\Models\Place;
use App\Models\Review;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class PlaceSeeder extends Seeder
{
    public function run(): void
    {
        $warkopCategory = Category::where('slug', 'warkop-modern')->first();
        $cafeCategory = Category::where('slug', 'cozy-coffee-shop')->first();
        $coworkingCategory = Category::where('slug', 'coworking-study-space')->first();
        $libraryCategory = Category::where('slug', 'library-quiet-cafe')->first();

        $allAmenities = Amenity::all()->keyBy('slug');

        $places = [
            [
                'category_id' => $libraryCategory->id,
                'name' => 'Maraca Books and Coffee',
                'slug' => 'maraca-books-and-coffee',
                'address' => 'Jl. Jalak Harupat No.9a, Babakan, Kecamatan Bogor Tengah, Kota Bogor',
                'subdistrict' => 'Bogor Tengah',
                'latitude' => -6.5912400,
                'longitude' => 106.7998100,
                'google_maps_url' => 'https://maps.app.goo.gl/maraca-bogor',
                'instagram_handle' => '@maracacoffee',
                'price_min_drink' => 18000,
                'price_max_drink' => 32000,
                'price_avg_food' => 25000,
                'price_tier' => 2,
                'parking_fee_motor' => 2000,
                'has_student_discount' => true,
                'wifi_speed_mbps' => 45,
                'wifi_quality' => 'fast',
                'plug_availability' => 'abundant',
                'noise_level' => 'quiet',
                'is_24_hours' => false,
                'open_time' => '08:00:00',
                'close_time' => '22:00:00',
                'google_rating' => 4.70,
                'total_google_reviews' => 1250,
                'nugas_score' => 92.5,
                'budget_score' => 82.0,
                'facility_score' => 94.0,
                'image_url' => 'https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=600&auto=format&fit=crop&q=80',
                'description' => 'Tempat nugas favorit mahasiswa IPB & Pakuan. Koleksi buku lengkap, suasana hening, colokan di tiap meja, dan kopi yang nikmat.',
                'vibe_tags' => 'Quiet, Book Cafe, Colokan Tiap Meja, AC Dingin, Skripsi Spot',
                'amenities' => ['colokan-melimpah', 'wifi-cepat', 'ruang-hening', 'ac-room', 'musholla', 'diskon-ktm'],
                'reviews' => [
                    ['reviewer_name' => 'Adit P.', 'rating' => 5.0, 'comment' => 'Tempat paling tenang buat garap skripsi di Bogor. Wi-Fi kenceng dan colokan di mana-mana.', 'sentiment' => 'positive', 'keywords' => 'tenang, skripsi, wifi kenceng, colokan'],
                    ['reviewer_name' => 'Siti N.', 'rating' => 4.5, 'comment' => 'Kopi susunya pas di kantong mahasiswa, ada diskon KTM 10%.', 'sentiment' => 'positive', 'keywords' => 'diskon ktm, kopi susu murah'],
                ],
            ],
            [
                'category_id' => $cafeCategory->id,
                'name' => 'Popolo Coffee Taman Kencana',
                'slug' => 'popolo-coffee-taman-kencana',
                'address' => 'Jl. Loader No.9, Baranangsiang, Kec. Bogor Timur, Kota Bogor',
                'subdistrict' => 'Bogor Timur',
                'latitude' => -6.5983500,
                'longitude' => 106.8081200,
                'google_maps_url' => 'https://maps.app.goo.gl/popolo-bogor',
                'instagram_handle' => '@popolocoffee',
                'price_min_drink' => 24000,
                'price_max_drink' => 42000,
                'price_avg_food' => 35000,
                'price_tier' => 2,
                'parking_fee_motor' => 2000,
                'has_student_discount' => false,
                'wifi_speed_mbps' => 60,
                'wifi_quality' => 'fast',
                'plug_availability' => 'moderate',
                'noise_level' => 'moderate',
                'is_24_hours' => false,
                'open_time' => '09:00:00',
                'close_time' => '21:00:00',
                'google_rating' => 4.65,
                'total_google_reviews' => 2340,
                'nugas_score' => 86.0,
                'budget_score' => 70.0,
                'facility_score' => 88.0,
                'image_url' => 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=600&auto=format&fit=crop&q=80',
                'description' => 'Coffee shop dengan suasana glassy house & taman asri. Enak untuk meeting santai atau nugas di area indoor ber-AC.',
                'vibe_tags' => 'Glasshouse, Aesthetic, Kopi Spesialis, Adem',
                'amenities' => ['wifi-cepat', 'ac-room', 'kursi-nyaman', 'parkir-motor-luas', 'smoking-area'],
                'reviews' => [
                    ['reviewer_name' => 'Farhan K.', 'rating' => 4.5, 'comment' => 'Vibe-nya cozy parah. Kalau mau nugas mending datang pagi atau weekday biar dapet meja indoor bercolokan.', 'sentiment' => 'positive', 'keywords' => 'cozy, wifi stabil, kopi enak'],
                ],
            ],
            [
                'category_id' => $warkopCategory->id,
                'name' => 'Warkop Berkah Nusantara 24 Jam',
                'slug' => 'warkop-berkah-nusantara-24-jam',
                'address' => 'Jl. Pajajaran Indah V No.12, Baranangsiang, Kec. Bogor Timur, Kota Bogor',
                'subdistrict' => 'Bogor Timur',
                'latitude' => -6.6062100,
                'longitude' => 106.8124500,
                'google_maps_url' => 'https://maps.app.goo.gl/warkop-berkah-bogor',
                'instagram_handle' => '@warkopberkah.bgr',
                'price_min_drink' => 6000,
                'price_max_drink' => 15000,
                'price_avg_food' => 14000,
                'price_tier' => 1,
                'parking_fee_motor' => 0,
                'has_student_discount' => false,
                'wifi_speed_mbps' => 35,
                'wifi_quality' => 'medium',
                'plug_availability' => 'abundant',
                'noise_level' => 'lively',
                'is_24_hours' => true,
                'open_time' => null,
                'close_time' => null,
                'google_rating' => 4.50,
                'total_google_reviews' => 620,
                'nugas_score' => 88.0,
                'budget_score' => 98.0,
                'facility_score' => 78.0,
                'image_url' => 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=600&auto=format&fit=crop&q=80',
                'description' => 'Penyelamat tugas tengah malam & akhir bulan. Buka 24 jam nonstop, indomie & kopi murah meriah, colokan kabel rol berlimpah di tiap meja.',
                'vibe_tags' => 'Buka 24 Jam, Super Hemat, Colokan Banyak, Indomie Dokdok, Parkir Gratis',
                'amenities' => ['colokan-melimpah', 'buka-24-jam', 'menu-hemat', 'parkir-gratis', 'smoking-area'],
                'reviews' => [
                    ['reviewer_name' => 'Budi Santoso', 'rating' => 5.0, 'comment' => 'Langganan begadang ngerjain project. Colokan banyak banget dan kopi item cuma 6 ribu.', 'sentiment' => 'positive', 'keywords' => '24 jam, murah, colokan banyak, begadang'],
                ],
            ],
            [
                'category_id' => $coworkingCategory->id,
                'name' => 'Daily Brew & Coworking Hub',
                'slug' => 'daily-brew-coworking-hub',
                'address' => 'Jl. Pandu Raya No.45, Tegal Gundil, Kec. Bogor Utara, Kota Bogor',
                'subdistrict' => 'Bogor Utara',
                'latitude' => -6.5781200,
                'longitude' => 106.8115400,
                'google_maps_url' => 'https://maps.app.goo.gl/dailybrew-bogor',
                'instagram_handle' => '@dailybrewhub',
                'price_min_drink' => 20000,
                'price_max_drink' => 38000,
                'price_avg_food' => 28000,
                'price_tier' => 2,
                'parking_fee_motor' => 2000,
                'has_student_discount' => true,
                'wifi_speed_mbps' => 100,
                'wifi_quality' => 'ultra',
                'plug_availability' => 'abundant',
                'noise_level' => 'quiet',
                'is_24_hours' => false,
                'open_time' => '08:30:00',
                'close_time' => '23:00:00',
                'google_rating' => 4.80,
                'total_google_reviews' => 840,
                'nugas_score' => 95.0,
                'budget_score' => 78.0,
                'facility_score' => 98.0,
                'image_url' => 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=600&auto=format&fit=crop&q=80',
                'description' => 'Dedicated workspace ramah mahasiswa di area Pandu Raya. Kecepatan Wi-Fi 100 Mbps simetris, ada private call pod & meja standing.',
                'vibe_tags' => 'Coworking, High Speed Wifi, Silent Room, Kursi Ergonomis, Colokan Tiap Meja',
                'amenities' => ['colokan-melimpah', 'wifi-cepat', 'kursi-nyaman', 'ruang-hening', 'ac-room', 'musholla', 'diskon-ktm'],
                'reviews' => [
                    ['reviewer_name' => 'Maya W.', 'rating' => 5.0, 'comment' => 'Internetnya luar biasa ngebut, upload file video tugas hitungan detik. Kursinya nyaman banget.', 'sentiment' => 'positive', 'keywords' => 'internet ngebut 100mbps, kursi nyaman, ruang hening'],
                ],
            ],
            [
                'category_id' => $cafeCategory->id,
                'name' => 'Uncle Jo X Bar Suryakencana',
                'slug' => 'uncle-jo-x-bar-suryakencana',
                'address' => 'Jl. Suryakencana No.15, Gudang, Kec. Bogor Tengah, Kota Bogor',
                'subdistrict' => 'Bogor Tengah',
                'latitude' => -6.6021500,
                'longitude' => 106.7989000,
                'google_maps_url' => 'https://maps.app.goo.gl/unclejo-surken',
                'instagram_handle' => '@unclejoxbar',
                'price_min_drink' => 15000,
                'price_max_drink' => 28000,
                'price_avg_food' => 22000,
                'price_tier' => 1,
                'parking_fee_motor' => 2000,
                'has_student_discount' => false,
                'wifi_speed_mbps' => 40,
                'wifi_quality' => 'medium',
                'plug_availability' => 'moderate',
                'noise_level' => 'moderate',
                'is_24_hours' => false,
                'open_time' => '08:00:00',
                'close_time' => '22:00:00',
                'google_rating' => 4.60,
                'total_google_reviews' => 1100,
                'nugas_score' => 84.5,
                'budget_score' => 88.0,
                'facility_score' => 82.0,
                'image_url' => 'https://images.unsplash.com/photo-1559925393-8be0ec4767c8?w=600&auto=format&fit=crop&q=80',
                'description' => 'Hidden gem di gang Suryakencana. Nuansa vintage heritage, kopi manual brew affordable, dan tempat santai untuk nugas sore.',
                'vibe_tags' => 'Vintage, Heritage Surken, Affordable Coffee, Santai',
                'amenities' => ['colokan-melimpah', 'wifi-cepat', 'ac-room', 'smoking-area'],
                'reviews' => [
                    ['reviewer_name' => 'Rian H.', 'rating' => 4.5, 'comment' => 'Kopi Jo-nya enak dan terjangkau banget. Vibe klasik Suryakencana bikin fresh.', 'sentiment' => 'positive', 'keywords' => 'kopi murah, vintage, nyaman'],
                ],
            ],
            [
                'category_id' => $cafeCategory->id,
                'name' => 'Kopi Nako Pajajaran Bogor',
                'slug' => 'kopi-nako-pajajaran-bogor',
                'address' => 'Jl. Pajajaran Indah V No.7, Baranangsiang, Kec. Bogor Timur, Kota Bogor',
                'subdistrict' => 'Bogor Timur',
                'latitude' => -6.6048900,
                'longitude' => 106.8118900,
                'google_maps_url' => 'https://maps.app.goo.gl/kopinako-bogor',
                'instagram_handle' => '@kopinako.id',
                'price_min_drink' => 19000,
                'price_max_drink' => 35000,
                'price_avg_food' => 30000,
                'price_tier' => 2,
                'parking_fee_motor' => 2000,
                'has_student_discount' => false,
                'wifi_speed_mbps' => 50,
                'wifi_quality' => 'fast',
                'plug_availability' => 'moderate',
                'noise_level' => 'lively',
                'is_24_hours' => false,
                'open_time' => '08:00:00',
                'close_time' => '23:00:00',
                'google_rating' => 4.60,
                'total_google_reviews' => 4500,
                'nugas_score' => 81.0,
                'budget_score' => 76.0,
                'facility_score' => 84.0,
                'image_url' => 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&auto=format&fit=crop&q=80',
                'description' => 'Ikonik dengan arsitektur kaca nako dan area outdoor rindang di bawah pepohonan. Cocok untuk nugas kelompok atau kerja santai.',
                'vibe_tags' => 'Nongkrong Kelompok, Outdoor Rindang, Kopi Susu Nako',
                'amenities' => ['wifi-cepat', 'ac-room', 'musholla', 'parkir-motor-luas', 'smoking-area'],
                'reviews' => [
                    ['reviewer_name' => 'Dimas T.', 'rating' => 4.0, 'comment' => 'Tempat luas banget, musholla bersih. Kalau mau hening pilih area kaca indoor lantai 2.', 'sentiment' => 'positive', 'keywords' => 'musholla bersih, tempat luas, es kopi nako'],
                ],
            ],
            [
                'category_id' => $warkopCategory->id,
                'name' => 'Warkop Modern Dramaga Border',
                'slug' => 'warkop-modern-dramaga-border',
                'address' => 'Jl. Raya Dramaga No.88, Margajaya, Kec. Bogor Barat, Kota Bogor',
                'subdistrict' => 'Bogor Barat',
                'latitude' => -6.5742100,
                'longitude' => 106.7456700,
                'google_maps_url' => 'https://maps.app.goo.gl/warkop-dramaga',
                'instagram_handle' => '@warkopmodern.dramaga',
                'price_min_drink' => 7000,
                'price_max_drink' => 16000,
                'price_avg_food' => 15000,
                'price_tier' => 1,
                'parking_fee_motor' => 0,
                'has_student_discount' => true,
                'wifi_speed_mbps' => 30,
                'wifi_quality' => 'medium',
                'plug_availability' => 'abundant',
                'noise_level' => 'moderate',
                'is_24_hours' => true,
                'open_time' => null,
                'close_time' => null,
                'google_rating' => 4.55,
                'total_google_reviews' => 410,
                'nugas_score' => 89.0,
                'budget_score' => 96.0,
                'facility_score' => 80.0,
                'image_url' => 'https://images.unsplash.com/photo-1541167760496-1628856ab772?w=600&auto=format&fit=crop&q=80',
                'description' => 'Titik kumpul mahasiswa IPB Dramaga. Dekat kampus, buka 24 jam, colokan siap pakai di setiap baris meja panjang.',
                'vibe_tags' => 'Dekat IPB, Mahasiswa Spot, 24 Jam, Colokan Melimpah, Parkir Gratis',
                'amenities' => ['colokan-melimpah', 'buka-24-jam', 'menu-hemat', 'diskon-ktm', 'parkir-gratis', 'smoking-area'],
                'reviews' => [
                    ['reviewer_name' => 'Fikri IPB', 'rating' => 5.0, 'comment' => 'Spot andalan anak IPB semester akhir. Wi-fi lancar, colokan gak pernah rebutan.', 'sentiment' => 'positive', 'keywords' => 'anak ipb, wifi lancar, colokan banyak'],
                ],
            ],
            [
                'category_id' => $coworkingCategory->id,
                'name' => 'Third Wave Coffee & Creative Lab',
                'slug' => 'third-wave-coffee-creative-lab',
                'address' => 'Jl. Achmad Adnawijaya No.102, Tegal Gundil, Kec. Bogor Utara, Kota Bogor',
                'subdistrict' => 'Bogor Utara',
                'latitude' => -6.5756300,
                'longitude' => 106.8142100,
                'google_maps_url' => 'https://maps.app.goo.gl/thirdwave-bogor',
                'instagram_handle' => '@thirdwave.lab',
                'price_min_drink' => 22000,
                'price_max_drink' => 45000,
                'price_avg_food' => 32000,
                'price_tier' => 2,
                'parking_fee_motor' => 2000,
                'has_student_discount' => true,
                'wifi_speed_mbps' => 80,
                'wifi_quality' => 'ultra',
                'plug_availability' => 'abundant',
                'noise_level' => 'quiet',
                'is_24_hours' => false,
                'open_time' => '08:00:00',
                'close_time' => '22:30:00',
                'google_rating' => 4.75,
                'total_google_reviews' => 760,
                'nugas_score' => 93.0,
                'budget_score' => 76.0,
                'facility_score' => 96.0,
                'image_url' => 'https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?w=600&auto=format&fit=crop&q=80',
                'description' => 'Tempat kerja kondusif dengan interior industrial minimalis. Meja luas, pencahayaan hangat dan tidak silau untuk mata di depan laptop.',
                'vibe_tags' => 'Industrial, High Speed Wi-Fi, Meja Luas, Kopi Manual Brew',
                'amenities' => ['colokan-melimpah', 'wifi-cepat', 'kursi-nyaman', 'ruang-hening', 'ac-room', 'musholla', 'diskon-ktm'],
                'reviews' => [
                    ['reviewer_name' => 'Sarah A.', 'rating' => 5.0, 'comment' => 'Mejanya lebar muat 2 laptop + buku catatan. Lampu mejanya enak gak bikin pusing.', 'sentiment' => 'positive', 'keywords' => 'meja lebar, wifi kenceng, nugas fokus'],
                ],
            ],
            [
                'category_id' => $cafeCategory->id,
                'name' => 'Coffee Toffee Pajajaran 24 Jam',
                'slug' => 'coffee-toffee-pajajaran-24-jam',
                'address' => 'Jl. Raya Pajajaran No.67, Babakan, Kec. Bogor Tengah, Kota Bogor',
                'subdistrict' => 'Bogor Tengah',
                'latitude' => -6.5898000,
                'longitude' => 106.8041000,
                'google_maps_url' => 'https://maps.app.goo.gl/coffeetoffee-bogor',
                'instagram_handle' => '@coffeetoffeeidn',
                'price_min_drink' => 20000,
                'price_max_drink' => 38000,
                'price_avg_food' => 28000,
                'price_tier' => 2,
                'parking_fee_motor' => 2000,
                'has_student_discount' => false,
                'wifi_speed_mbps' => 45,
                'wifi_quality' => 'fast',
                'plug_availability' => 'abundant',
                'noise_level' => 'moderate',
                'is_24_hours' => true,
                'open_time' => null,
                'close_time' => null,
                'google_rating' => 4.50,
                'total_google_reviews' => 1890,
                'nugas_score' => 90.0,
                'budget_score' => 80.0,
                'facility_score' => 91.0,
                'image_url' => 'https://images.unsplash.com/photo-1509785307050-d4066910ec1e?w=600&auto=format&fit=crop&q=80',
                'description' => 'Salah satu pionir cafe 24 jam di jalan protokol Pajajaran. Ruangan AC luas, meja kerja bersekat, dan Wi-Fi stabil sepanjang malam.',
                'vibe_tags' => 'Pajajaran, 24 Jam, AC Luas, Colokan Banyak, Pusat Kota',
                'amenities' => ['colokan-melimpah', 'wifi-cepat', 'buka-24-jam', 'ac-room', 'musholla', 'parkir-motor-luas'],
                'reviews' => [
                    ['reviewer_name' => 'Yoga P.', 'rating' => 4.5, 'comment' => 'Lokasi strategis di Pajajaran, selalu jadi pilihan kalau butuh tempat 24 jam ber-AC.', 'sentiment' => 'positive', 'keywords' => 'lokasi strategis, 24 jam, ac dingin'],
                ],
            ],
            [
                'category_id' => $libraryCategory->id,
                'name' => 'Bumi Aki Space & Study Lounge',
                'slug' => 'bumi-aki-space-study-lounge',
                'address' => 'Jl. Raya Pajajaran No.51, Bantarjati, Kec. Bogor Utara, Kota Bogor',
                'subdistrict' => 'Bogor Utara',
                'latitude' => -6.5824000,
                'longitude' => 106.8078000,
                'google_maps_url' => 'https://maps.app.goo.gl/bumiaki-space',
                'instagram_handle' => '@bumiaki.space',
                'price_min_drink' => 22000,
                'price_max_drink' => 40000,
                'price_avg_food' => 35000,
                'price_tier' => 2,
                'parking_fee_motor' => 2000,
                'has_student_discount' => true,
                'wifi_speed_mbps' => 55,
                'wifi_quality' => 'fast',
                'plug_availability' => 'abundant',
                'noise_level' => 'quiet',
                'is_24_hours' => false,
                'open_time' => '09:00:00',
                'close_time' => '22:00:00',
                'google_rating' => 4.70,
                'total_google_reviews' => 950,
                'nugas_score' => 91.0,
                'budget_score' => 74.0,
                'facility_score' => 95.0,
                'image_url' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=600&auto=format&fit=crop&q=80',
                'description' => 'Area lounge bernuansa hangat dengan tanaman hijau indoor. Banyak sudut hening untuk fokus membaca, menulis, atau meeting online.',
                'vibe_tags' => 'Greenery, Quiet Lounge, Warm Ambient, Fokus Belajar',
                'amenities' => ['colokan-melimpah', 'wifi-cepat', 'kursi-nyaman', 'ruang-hening', 'ac-room', 'musholla', 'diskon-ktm'],
                'reviews' => [
                    ['reviewer_name' => 'Nadia E.', 'rating' => 5.0, 'comment' => 'Suasananya adem banget, playlist musiknya instrumental santai gak berisik.', 'sentiment' => 'positive', 'keywords' => 'musik tenang, adem, fokus nugas'],
                ],
            ],
            [
                'category_id' => $cafeCategory->id,
                'name' => 'Raindear Coffee & Kitchen Baranangsiang',
                'slug' => 'raindear-coffee-kitchen-baranangsiang',
                'address' => 'Jl. Bina Marga I No.7, Baranangsiang, Kec. Bogor Timur, Kota Bogor',
                'subdistrict' => 'Bogor Timur',
                'latitude' => -6.6029000,
                'longitude' => 106.8142000,
                'google_maps_url' => 'https://maps.app.goo.gl/raindear-bogor',
                'instagram_handle' => '@raindearcoffee',
                'price_min_drink' => 25000,
                'price_max_drink' => 48000,
                'price_avg_food' => 40000,
                'price_tier' => 2,
                'parking_fee_motor' => 2000,
                'has_student_discount' => false,
                'wifi_speed_mbps' => 50,
                'wifi_quality' => 'fast',
                'plug_availability' => 'moderate',
                'noise_level' => 'moderate',
                'is_24_hours' => false,
                'open_time' => '07:00:00',
                'close_time' => '22:00:00',
                'google_rating' => 4.60,
                'total_google_reviews' => 3100,
                'nugas_score' => 82.0,
                'budget_score' => 68.0,
                'facility_score' => 86.0,
                'image_url' => 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=600&auto=format&fit=crop&q=80',
                'description' => 'Terkenal dengan Es Kopi Susu Bogor dan makanan lezat. Buka mulai jam 7 pagi, pas untuk mahasiswa yang ingin nugas sebelum kelas pagi.',
                'vibe_tags' => 'Buka Pagi, Es Kopi Susu Bogor, Spacious, Baranangsiang',
                'amenities' => ['wifi-cepat', 'ac-room', 'musholla', 'parkir-motor-luas', 'smoking-area'],
                'reviews' => [
                    ['reviewer_name' => 'Ferry A.', 'rating' => 4.5, 'comment' => 'Bagus buat nugas pagi-pagi sebelum jam 10 pas masih sepi dan adem.', 'sentiment' => 'positive', 'keywords' => 'nugas pagi, es kopi susu bogor, nyaman'],
                ],
            ],
            [
                'category_id' => $warkopCategory->id,
                'name' => 'Warkop Modern Yasmin Corner',
                'slug' => 'warkop-modern-yasmin-corner',
                'address' => 'Jl. KH. R. Abdullah Bin Nuh No.33, Curugmekar, Kec. Bogor Barat, Kota Bogor',
                'subdistrict' => 'Bogor Barat',
                'latitude' => -6.5598000,
                'longitude' => 106.7723000,
                'google_maps_url' => 'https://maps.app.goo.gl/warkop-yasmin',
                'instagram_handle' => '@warkopyasmin',
                'price_min_drink' => 8000,
                'price_max_drink' => 18000,
                'price_avg_food' => 16000,
                'price_tier' => 1,
                'parking_fee_motor' => 0,
                'has_student_discount' => false,
                'wifi_speed_mbps' => 35,
                'wifi_quality' => 'medium',
                'plug_availability' => 'abundant',
                'noise_level' => 'moderate',
                'is_24_hours' => true,
                'open_time' => null,
                'close_time' => null,
                'google_rating' => 4.50,
                'total_google_reviews' => 520,
                'nugas_score' => 87.5,
                'budget_score' => 95.0,
                'facility_score' => 78.0,
                'image_url' => 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80',
                'description' => 'Tempat santai di koridor Yasmin - Abdullah Bin Nuh. Buka 24 jam dengan Wi-Fi stabil, toast cokelat keju, dan kopi robusta hemat.',
                'vibe_tags' => 'Yasmin, 24 Jam, Roti Bakar, Parkir Gratis, Murah',
                'amenities' => ['colokan-melimpah', 'buka-24-jam', 'menu-hemat', 'parkir-gratis', 'smoking-area'],
                'reviews' => [
                    ['reviewer_name' => 'Hendra S.', 'rating' => 4.5, 'comment' => 'Pilihan tepat buat yang tinggal di daerah Yasmin. Murah meriah dan colokan aman.', 'sentiment' => 'positive', 'keywords' => 'murah, yasmin, colokan aman'],
                ],
            ],
            [
                'category_id' => $coworkingCategory->id,
                'name' => 'Code & Coffee Worklab Tanah Sareal',
                'slug' => 'code-coffee-worklab-tanah-sareal',
                'address' => 'Jl. Kebon Pedes No.18, Kebon Pedes, Kec. Tanah Sareal, Kota Bogor',
                'subdistrict' => 'Tanah Sareal',
                'latitude' => -6.5712000,
                'longitude' => 106.7943000,
                'google_maps_url' => 'https://maps.app.goo.gl/codecoffee-tansar',
                'instagram_handle' => '@codecoffee.bogor',
                'price_min_drink' => 18000,
                'price_max_drink' => 32000,
                'price_avg_food' => 24000,
                'price_tier' => 2,
                'parking_fee_motor' => 2000,
                'has_student_discount' => true,
                'wifi_speed_mbps' => 90,
                'wifi_quality' => 'ultra',
                'plug_availability' => 'abundant',
                'noise_level' => 'quiet',
                'is_24_hours' => false,
                'open_time' => '09:00:00',
                'close_time' => '23:00:00',
                'google_rating' => 4.85,
                'total_google_reviews' => 490,
                'nugas_score' => 94.5,
                'budget_score' => 84.0,
                'facility_score' => 97.0,
                'image_url' => 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=600&auto=format&fit=crop&q=80',
                'description' => 'Hub favorit coder dan mahasiswa IT. Dilengkapi colokan type-C, koneksi fiber optik gigabit, dan white board untuk diskusi tugas kelompok.',
                'vibe_tags' => 'Coding Spot, High Speed Fiber, Whiteboard, Silent Zone',
                'amenities' => ['colokan-melimpah', 'wifi-cepat', 'kursi-nyaman', 'ruang-hening', 'ac-room', 'musholla', 'diskon-ktm'],
                'reviews' => [
                    ['reviewer_name' => 'Fahmi IT', 'rating' => 5.0, 'comment' => 'Surga buat ngoding & nugas skripsi IT. Internet kencang tanpa lag, banyak colokan PD type-c.', 'sentiment' => 'positive', 'keywords' => 'ngoding, wifi kencang, colokan type-c, hening'],
                ],
            ],
            [
                'category_id' => $cafeCategory->id,
                'name' => 'Kopi Daong Heritage Space Batutulis',
                'slug' => 'kopi-daong-heritage-space-batutulis',
                'address' => 'Jl. Batutulis No.40, Batutulis, Kec. Bogor Selatan, Kota Bogor',
                'subdistrict' => 'Bogor Selatan',
                'latitude' => -6.6214000,
                'longitude' => 106.8065000,
                'google_maps_url' => 'https://maps.app.goo.gl/kopidaong-batutulis',
                'instagram_handle' => '@kopidaong.batutulis',
                'price_min_drink' => 20000,
                'price_max_drink' => 38000,
                'price_avg_food' => 30000,
                'price_tier' => 2,
                'parking_fee_motor' => 2000,
                'has_student_discount' => false,
                'wifi_speed_mbps' => 40,
                'wifi_quality' => 'medium',
                'plug_availability' => 'moderate',
                'noise_level' => 'moderate',
                'is_24_hours' => false,
                'open_time' => '10:00:00',
                'close_time' => '22:00:00',
                'google_rating' => 4.55,
                'total_google_reviews' => 880,
                'nugas_score' => 82.5,
                'budget_score' => 76.0,
                'facility_score' => 84.0,
                'image_url' => 'https://images.unsplash.com/photo-1507133750040-4a8f57021571?w=600&auto=format&fit=crop&q=80',
                'description' => 'Cabang kota dengan sentuhan pinus dan taman sejuk di Bogor Selatan. Udaranya sejuk alami, cocok untuk nugas santai sore hari.',
                'vibe_tags' => 'Bogor Selatan, Sejuk, Taman Pinus, Outdoor Cozy',
                'amenities' => ['wifi-cepat', 'musholla', 'parkir-motor-luas', 'smoking-area'],
                'reviews' => [
                    ['reviewer_name' => 'Indra K.', 'rating' => 4.5, 'comment' => 'Udaranya sejuk di sore hari, cocok buat nulis atau ngobrol santai sama temen kelompok.', 'sentiment' => 'positive', 'keywords' => 'sejuk, nugas sore, outdoor adem'],
                ],
            ],
        ];

        foreach ($places as $placeData) {
            $amenitiesSlugs = $placeData['amenities'] ?? [];
            $reviewsData = $placeData['reviews'] ?? [];
            unset($placeData['amenities'], $placeData['reviews']);

            $place = Place::updateOrCreate(
                ['slug' => $placeData['slug']],
                $placeData
            );

            // Attach amenities
            if (!empty($amenitiesSlugs)) {
                $attachMap = [];
                foreach ($amenitiesSlugs as $slug) {
                    if (isset($allAmenities[$slug])) {
                        $attachMap[$allAmenities[$slug]->id] = ['detail' => 'Tersedia di lokasi'];
                    }
                }
                $place->amenities()->sync($attachMap);
            }

            // Create sample reviews
            if (!empty($reviewsData)) {
                foreach ($reviewsData as $rev) {
                    Review::updateOrCreate(
                        ['place_id' => $place->id, 'reviewer_name' => $rev['reviewer_name']],
                        [
                            'source' => 'google',
                            'rating' => $rev['rating'],
                            'comment' => $rev['comment'],
                            'sentiment' => $rev['sentiment'],
                            'extracted_keywords' => $rev['keywords'],
                        ]
                    );
                }
            }
        }
    }
}
