/**
 * MOCK DATA — Admin pages (Dashboard, Kelola Kafe, Tiket, Analisis)
 *
 * This data is used only because no admin backend API exists yet.
 * When the admin API is available, replace the data hooks in each
 * admin feature to call the API instead of importing from this file.
 *
 * DO NOT import this file from lib/api.ts or any API layer.
 */

export const ADMIN_STORAGE_KEY = 'goaround_admin_store_v3';

export const MOCK_KPI = {
  totalKafe: 13,
  totalKafeChange: '+3 bulan ini',
  totalKafeBreakdown: 'Bgr Tengah (3), Bgr Timur (4), Bgr Utara (3), Lainnya (3)',
  tiketTerbuka: 4,
  tiketNote: 'Perlu validasi',
  tiketBreakdown: '1 wifi drop, 1 colokan mati, 1 usulan, 1 jam buka',
  usulanBaru: 1,
  usulanNote: 'Menunggu Review',
  usulanBreakdown: 'Masuk dari koridor Yasmin (Bogor Barat)',
  kunjungan: 1420,
  kunjunganNote: 'sesi hari ini',
  kunjunganBreakdown: '312 unduhan rute GIS & bookmark kafe',
};

export const MOCK_PLACES_TABLE = [
  {
    id: 1001,
    code: 'KF-001',
    name: 'Maraca Books and Coffee',
    address: 'Jl. Jalak Harupat No. 9A, Babakan, Bogor Tengah',
    lat: -6.59124,
    lng: 106.79981,
    wifi: 45,
    plug: 95,
    plugLabel: 'Colokan tiap meja',
    price: 'Rp 18.000+',
    priceCategory: 'Diskon KTM',
    acoustic: 'Tenang',
    score: 9.3,
    status: 'verified' as const,
    district: 'Bogor Tengah',
    is24Hours: false,
    imageUrl: 'https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 1002,
    code: 'KF-002',
    name: 'Popolo Coffee Taman Kencana',
    address: 'Jl. Loader No. 9, Baranangsiang, Bogor Timur',
    lat: -6.59835,
    lng: 106.80812,
    wifi: 60,
    plug: 75,
    plugLabel: 'Cukup memadai',
    price: 'Rp 24.000+',
    priceCategory: 'Standar Kafe',
    acoustic: 'Kondusif',
    score: 8.6,
    status: 'verified' as const,
    district: 'Bogor Timur',
    is24Hours: false,
    imageUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 1003,
    code: 'KF-003',
    name: 'Warkop Berkah Nusantara 24 Jam',
    address: 'Jl. Pajajaran Indah V No. 12, Baranangsiang, Bogor Timur',
    lat: -6.60621,
    lng: 106.81245,
    wifi: 35,
    plug: 92,
    plugLabel: 'Colokan melimpah',
    price: 'Rp 6.000+',
    priceCategory: 'Super Hemat',
    acoustic: 'Ramai Malam',
    score: 8.8,
    status: 'verified' as const,
    district: 'Bogor Timur',
    is24Hours: true,
    imageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 1004,
    code: 'KF-004',
    name: 'Daily Brew & Coworking Hub',
    address: 'Jl. Pandu Raya No. 45, Tegal Gundil, Bogor Utara',
    lat: -6.57812,
    lng: 106.81154,
    wifi: 100,
    plug: 98,
    plugLabel: 'Tiap meja kerja',
    price: 'Rp 20.000+',
    priceCategory: 'Diskon KTM',
    acoustic: 'Ruang Hening',
    score: 9.5,
    status: 'verified' as const,
    district: 'Bogor Utara',
    is24Hours: false,
    imageUrl: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 1005,
    code: 'KF-005',
    name: 'Uncle Jo X Bar Suryakencana',
    address: 'Jl. Suryakencana No. 15, Gudang, Bogor Tengah',
    lat: -6.60215,
    lng: 106.79890,
    wifi: 40,
    plug: 76,
    plugLabel: 'Cukup memadai',
    price: 'Rp 15.000+',
    priceCategory: 'Ramah Mahasiswa',
    acoustic: 'Kondusif',
    score: 8.5,
    status: 'verified' as const,
    district: 'Bogor Tengah',
    is24Hours: false,
    imageUrl: 'https://images.unsplash.com/photo-1559925393-8be0ec4767c8?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 1006,
    code: 'KF-006',
    name: 'Kopi Nako Pajajaran Bogor',
    address: 'Jl. Pajajaran Indah V No. 7, Baranangsiang, Bogor Timur',
    lat: -6.60489,
    lng: 106.81189,
    wifi: 50,
    plug: 72,
    plugLabel: 'Area kaca indoor',
    price: 'Rp 19.000+',
    priceCategory: 'Ramah Mahasiswa',
    acoustic: 'Kerja Kelompok',
    score: 8.1,
    status: 'verified' as const,
    district: 'Bogor Timur',
    is24Hours: false,
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 1007,
    code: 'KF-007',
    name: 'Third Wave Coffee & Creative Lab',
    address: 'Jl. Achmad Adnawijaya No. 102, Tegal Gundil, Bogor Utara',
    lat: -6.57563,
    lng: 106.81421,
    wifi: 80,
    plug: 94,
    plugLabel: 'Meja lebar & colokan',
    price: 'Rp 22.000+',
    priceCategory: 'Diskon KTM',
    acoustic: 'Tenang',
    score: 9.3,
    status: 'verified' as const,
    district: 'Bogor Utara',
    is24Hours: false,
    imageUrl: 'https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 1008,
    code: 'KF-008',
    name: 'Coffee Toffee Pajajaran 24 Jam',
    address: 'Jl. Raya Pajajaran No. 67, Babakan, Bogor Tengah',
    lat: -6.58980,
    lng: 106.80410,
    wifi: 45,
    plug: 90,
    plugLabel: 'Hampir tiap meja',
    price: 'Rp 20.000+',
    priceCategory: 'Ramah Mahasiswa',
    acoustic: 'Kondusif',
    score: 9.0,
    status: 'verified' as const,
    district: 'Bogor Tengah',
    is24Hours: true,
    imageUrl: 'https://images.unsplash.com/photo-1509785307050-d4066910ec1e?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 1009,
    code: 'KF-009',
    name: 'Bumi Aki Space & Study Lounge',
    address: 'Jl. Raya Pajajaran No. 51, Bantarjati, Bogor Utara',
    lat: -6.58240,
    lng: 106.80780,
    wifi: 55,
    plug: 90,
    plugLabel: 'Colokan tiap sudut',
    price: 'Rp 22.000+',
    priceCategory: 'Diskon KTM',
    acoustic: 'Sangat Tenang',
    score: 9.1,
    status: 'verified' as const,
    district: 'Bogor Utara',
    is24Hours: false,
    imageUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 1010,
    code: 'KF-010',
    name: 'Raindear Coffee & Kitchen Baranangsiang',
    address: 'Jl. Bina Marga I No. 7, Baranangsiang, Bogor Timur',
    lat: -6.60290,
    lng: 106.81420,
    wifi: 50,
    plug: 74,
    plugLabel: 'Cukup memadai',
    price: 'Rp 25.000+',
    priceCategory: 'Standar Kafe',
    acoustic: 'Kondusif Pagi',
    score: 8.2,
    status: 'verified' as const,
    district: 'Bogor Timur',
    is24Hours: false,
    imageUrl: 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 1011,
    code: 'KF-011',
    name: 'Warkop Modern Yasmin Corner',
    address: 'Jl. KH. R. Abdullah Bin Nuh No. 33, Curugmekar, Bogor Barat',
    lat: -6.55980,
    lng: 106.77230,
    wifi: 35,
    plug: 88,
    plugLabel: 'Banyak colokan',
    price: 'Rp 8.000+',
    priceCategory: 'Super Hemat',
    acoustic: 'Santai',
    score: 8.8,
    status: 'review' as const,
    district: 'Bogor Barat',
    is24Hours: true,
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 1012,
    code: 'KF-012',
    name: 'Code & Coffee Worklab Tanah Sareal',
    address: 'Jl. Kebon Pedes No. 18, Kebon Pedes, Tanah Sareal',
    lat: -6.57120,
    lng: 106.79430,
    wifi: 90,
    plug: 96,
    plugLabel: 'Colokan + USB-C',
    price: 'Rp 18.000+',
    priceCategory: 'Diskon KTM',
    acoustic: 'Silent Zone',
    score: 9.5,
    status: 'verified' as const,
    district: 'Tanah Sareal',
    is24Hours: false,
    imageUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 1013,
    code: 'KF-013',
    name: 'Kopi Daong Heritage Space Batutulis',
    address: 'Jl. Batutulis No. 40, Batutulis, Bogor Selatan',
    lat: -6.62140,
    lng: 106.80650,
    wifi: 40,
    plug: 70,
    plugLabel: 'Area semi-indoor',
    price: 'Rp 20.000+',
    priceCategory: 'Ramah Mahasiswa',
    acoustic: 'Sejuk Tenang',
    score: 8.3,
    status: 'verified' as const,
    district: 'Bogor Selatan',
    is24Hours: false,
    imageUrl: 'https://images.unsplash.com/photo-1507133750040-4a8f57021571?w=400&auto=format&fit=crop&q=80',
  },
];

export const MOCK_ADMIN_TICKETS = [
  {
    id: 'TK-802',
    priority: 'high' as const,
    category: 'Colokan Rusak',
    cafeName: 'Maraca Books and Coffee',
    location: 'Babakan, Bogor Tengah',
    timeAgo: '24 menit yang lalu',
    reportedBy: 'Anonim',
    description:
      'Colokan di meja sudut ruang baca lantai 2 ada 3 titik yang longgar dan mati total saat dipakai cas laptop.',
  },
  {
    id: 'TK-795',
    priority: 'medium' as const,
    category: 'WiFi Tidak Stabil',
    cafeName: 'Kopi Nako Pajajaran Bogor',
    location: 'Baranangsiang, Bogor Timur',
    timeAgo: '1 jam lalu',
    reportedBy: 'Anonim',
    description:
      'WiFi di area kaca indoor sempat ngedrop ke 12 Mbps saat jam ramai sore (18.30 WIB), padahal di WebGIS tertulis 50 Mbps.',
  },
  {
    id: 'TK-791',
    priority: 'suggestion' as const,
    category: 'Usulan Spot Nugas Baru',
    cafeName: 'Ruang Sore Pajajaran',
    location: 'Jl. Raya Pajajaran, Bogor Tengah',
    timeAgo: '3 jam yang lalu',
    reportedBy: 'Anonim',
    description:
      'Usulan pembaruan atribut harga minuman (Rp 18.000 - Rp 30.000) dan verifikasi tambahan titik colokan di area indoor.',
  },
  {
    id: 'TK-788',
    priority: 'low' as const,
    category: 'Update Jam Operasional',
    cafeName: 'Coffee Toffee Pajajaran 24 Jam',
    location: 'Babakan, Bogor Tengah',
    timeAgo: '5 jam yang lalu',
    reportedBy: 'Anonim',
    description:
      'Area lantai 2 sekarang tetap dibuka 24 jam penuh saat hari kerja untuk mahasiswa nugas malam.',
  },
];

export const MOCK_ANALYTICS = {
  kpi: {
    totalQueries: 28450,
    queriesGrowth: '+18% bulan ini',
    activeStudents: 14210,
    studentsGrowth: '+12.4%',
    avgSessionHours: 4.2,
    routeConversions: 6840,
    conversionRate: '24.0%',
  },
  preferences: [
    { label: 'WiFi Cepat (>50 Mbps)', percent: 78, hits: 25100, color: '#005B54' },
    { label: 'Banyak Colokan Listrik (>80% meja terpasang)', percent: 68, hits: 21880, color: '#005B54' },
    { label: 'Ramah Kantong Mahasiswa (< Rp 25.000 / minuman)', percent: 56, hits: 18010, color: '#D97706' },
    { label: 'Buka Larut Malam / 24 Jam', percent: 44, hits: 14150, color: '#64748B' },
    { label: 'Suasana Tenang / Tidak Berisik (<50 dB)', percent: 39, hits: 12540, color: '#64748B' },
  ],
  peakHours: [
    { label: 'Pagi\n08.00-11.00', percent: 15, isPeak: false },
    { label: 'Siang\n12.00-15.00', percent: 42, isPeak: false },
    { label: 'Sore - Malam\n16.00-21.00', percent: 88, isPeak: true },
    { label: 'Larut Malam\n22.00-02.00', percent: 32, isPeak: false },
  ],
  spatialDensity: [
    {
      rank: 1,
      area: 'Bogor Tengah (Babakan, Taman Kencana & Suryakencana)',
      queries: 11240,
      note: 'Konsentrasi utama sekitar Kampus SV IPB Cilibende, Lodaya & Sempur (39.5% total kueri)',
      color: '#005B54',
    },
    {
      rank: 2,
      area: 'Bogor Timur (Baranangsiang & Pajajaran Indah)',
      queries: 8420,
      note: 'Koridor Kampus IPB Baranangsiang, Universitas Pakuan & halte Biskita (29.6%)',
      color: '#D97706',
    },
    {
      rank: 3,
      area: 'Bogor Utara (Tegal Gundil, Pandu Raya & Bantarjati)',
      queries: 5120,
      note: 'Pusat coworking hub mahasiswa sekitar Kampus SV IPB Gunung Gede (18.0%)',
      color: '#64748B',
    },
    {
      rank: 4,
      area: 'Bogor Barat & Tanah Sareal (Yasmin & Kebon Pedes)',
      queries: 3670,
      note: 'Koridor warkop modern 24 jam & worklab di kawasan hunian mahasiswa (12.9%)',
      color: '#64748B',
    },
  ],
  topCafes: [
    { rank: 1, name: 'Maraca Books and Coffee', address: 'Jl. Jalak Harupat No. 9A, Babakan, Bogor Tengah', clicks: 2140 },
    { rank: 2, name: 'Daily Brew & Coworking Hub', address: 'Jl. Pandu Raya No. 45, Tegal Gundil, Bogor Utara', clicks: 1820 },
    { rank: 3, name: 'Popolo Coffee Taman Kencana', address: 'Jl. Loader No. 9, Baranangsiang, Bogor Timur', clicks: 1490 },
    { rank: 4, name: 'Coffee Toffee Pajajaran 24 Jam', address: 'Jl. Raya Pajajaran No. 67, Babakan, Bogor Tengah', clicks: 1210 },
    { rank: 5, name: 'Kopi Nako Pajajaran Bogor', address: 'Jl. Pajajaran Indah V No. 7, Baranangsiang, Bogor Timur', clicks: 980 },
  ],
};
