import type { PlaceListItem } from './types';

export const FIGMA_PLACES: PlaceListItem[] = [
  {
    id: 991,
    category_id: 1,
    name: 'Anthology Coffee & Tea',
    slug: 'anthology-coffee-tea',
    address: 'Jl. Danau Teratai, Kompleks Baranangsiang Indah, Kota Bogor',
    subdistrict: 'Baranangsiang',
    latitude: -6.6012,
    longitude: 106.8064,
    google_maps_url: 'https://maps.google.com/?q=Anthology+Coffee+Tea+Bogor',
    instagram_handle: '@anthologycoffee',
    price_min_drink: 18000,
    price_max_drink: 32000,
    price_avg_food: 28000,
    price_tier: 1,
    parking_fee_motor: 2000,
    has_student_discount: true,
    wifi_speed_mbps: 92,
    wifi_quality: 'ultra',
    plug_availability: 'abundant',
    noise_level: 'quiet',
    is_24_hours: false,
    open_time: '08:00:00',
    close_time: '22:00:00',
    google_rating: 4.8,
    total_google_reviews: 940,
    nugas_score: 97,
    budget_score: 96,
    facility_score: 98,
    image_url: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&auto=format&fit=crop&q=80',
    description: 'Tempat paling pas dengan kriteria mahasiswa: colokan melimpah di bawah meja, musik lofi instrumental stabil, AC dingin, dan es kopi susu Rp20.000 sangat bersahabat untuk sesi nugas panjang.',
    vibe_tags: 'Colokan Tiap Meja, WiFi Kenceng, Tenang Kondusif, Es Kopi Murah',
    status: 'active',
    created_at: '2026-08-01T00:00:00Z',
    updated_at: '2026-08-01T00:00:00Z',
    category: {
      id: 1,
      name: 'Cozy Coffee Shop',
      slug: 'cozy-coffee-shop',
      icon: 'coffee',
    },
    amenities: [],
  },
  {
    id: 992,
    category_id: 1,
    name: 'Kopi Nako Dampingan',
    slug: 'kopi-nako-dampingan',
    address: 'Jl. Pajajaran No. 28, Baranangsiang, Kota Bogor',
    subdistrict: 'Bogor Timur',
    latitude: -6.6045,
    longitude: 106.8123,
    google_maps_url: 'https://maps.google.com/?q=Kopi+Nako+Pajajaran+Bogor',
    instagram_handle: '@kopinako.bogor',
    price_min_drink: 15000,
    price_max_drink: 28000,
    price_avg_food: 25000,
    price_tier: 1,
    parking_fee_motor: 2000,
    has_student_discount: true,
    wifi_speed_mbps: 78,
    wifi_quality: 'fast',
    plug_availability: 'moderate',
    noise_level: 'moderate',
    is_24_hours: false,
    open_time: '08:00:00',
    close_time: '23:00:00',
    google_rating: 4.6,
    total_google_reviews: 1420,
    nugas_score: 94,
    budget_score: 92,
    facility_score: 95,
    image_url: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&auto=format&fit=crop&q=80',
    description: 'Cafe luas dengan suasana semi-outdoor adem, colokan tersebar di area indoor, dan es kopi ramah kantong mahasiswa.',
    vibe_tags: 'Outdoor Adem, Colokan Tersebar, Buka sd 23:00',
    status: 'active',
    created_at: '2026-08-01T00:00:00Z',
    updated_at: '2026-08-01T00:00:00Z',
    category: {
      id: 1,
      name: 'Cozy Coffee Shop',
      slug: 'cozy-coffee-shop',
      icon: 'coffee',
    },
    amenities: [],
  },
  {
    id: 993,
    category_id: 1,
    name: 'Popolo Coffee Pajajaran',
    slug: 'popolo-coffee-pajajaran',
    address: 'Jl. Lodaya I No. 4, Babakan, Kota Bogor',
    subdistrict: 'Bogor Tengah',
    latitude: -6.5912,
    longitude: 106.8042,
    google_maps_url: 'https://maps.google.com/?q=Popolo+Coffee+Lodaya',
    instagram_handle: '@popolocoffee',
    price_min_drink: 20000,
    price_max_drink: 35000,
    price_avg_food: 32000,
    price_tier: 2,
    parking_fee_motor: 2000,
    has_student_discount: false,
    wifi_speed_mbps: 85,
    wifi_quality: 'fast',
    plug_availability: 'abundant',
    noise_level: 'quiet',
    is_24_hours: false,
    open_time: '09:00:00',
    close_time: '21:00:00',
    google_rating: 4.7,
    total_google_reviews: 1100,
    nugas_score: 93,
    budget_score: 88,
    facility_score: 96,
    image_url: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=800&auto=format&fit=crop&q=80',
    description: 'Suasana tenang dengan pencahayaan alami, koneksi internet stabil dan meja ergonomis.',
    vibe_tags: 'Tiap Meja Indoor, Sangat Tenang, Kopi Spesialti',
    status: 'active',
    created_at: '2026-08-01T00:00:00Z',
    updated_at: '2026-08-01T00:00:00Z',
    category: {
      id: 1,
      name: 'Cozy Coffee Shop',
      slug: 'cozy-coffee-shop',
      icon: 'coffee',
    },
    amenities: [],
  },
];
