import {
  Laptop,
  BookOpen,
  Users,
  Moon,
  Zap,
  Wifi,
  Volume2,
  DollarSign,
} from 'lucide-react';

// ── Vibe / Kategori Nugas Data with Visual Spec Chips ──
export const STUDY_VIBES = [
  {
    id: 'work-friendly',
    title: 'Work-Friendly & Laptop Space',
    icon: Laptop,
    badge: 'Paling Diminati',
    badgeColor: 'bg-emerald-50 text-emerald-800 border-emerald-300',
    tagline: 'Dirancang khusus untuk laptopan berjam-jam tanpa khawatir kehabisan baterai.',
    specs: [
      { label: 'Ketersediaan Daya', level: 'Sangat Melimpah', status: 'optimal', desc: 'Colokan di >75% meja' },
      { label: 'Kestabilan Internet', level: 'Ultra-Fast 50+ Mbps', status: 'optimal', desc: 'Lancar video meeting' },
      { label: 'Kenyamanan Meja', level: 'Ergonomis Tinggi', status: 'optimal', desc: 'Kursi busa & meja proporsional' },
      { label: 'Ambiens Suara', level: 'Kondusif Sedang', status: 'good', desc: 'Obrolan wajar & musik tenang' },
    ],
    features: [
      'Stopkontak aktif di hampir setiap meja (rasio >75%)',
      'Tinggi meja dan kursi standar ergonomis untuk mengetik lama',
      'Wi-Fi stabil dengan bandwidth upload lancar untuk video call',
      'Pencahayaan terang dan sirkulasi pendingin ruangan sejuk',
    ],
    idealFor: 'Mengerjakan coding, analisis geospasial SIG, desain grafis, dan skripsi.',
    spots: ['Jl. Pajajaran Tengah', 'Jl. Bangbarung Raya', 'Suryakencana'],
  },
  {
    id: 'quiet-focus',
    title: 'Focus & Quiet Zone (Zona Hening)',
    icon: BookOpen,
    badge: 'Kondusif Skripsi',
    badgeColor: 'bg-teal-50 text-teal-800 border-teal-300',
    tagline: 'Ambiens tenang bebas kebisingan musik keras untuk konsentrasi tinggi.',
    specs: [
      { label: 'Ambiens Suara', level: 'Hening Total (35–45 dB)', status: 'optimal', desc: 'Bebas live music & bising' },
      { label: 'Privasi Ruang', level: 'Jarak Meja Luas', status: 'optimal', desc: 'Sudut baca menyendiri' },
      { label: 'Kestabilan Internet', level: 'Stabil 30+ Mbps', status: 'good', desc: 'Lancar riset jurnal e-book' },
      { label: 'Ketersediaan Daya', level: 'Tersedia di Meja Baca', status: 'good', desc: 'Stopkontak di meja khusus' },
    ],
    features: [
      'Tingkat kebisingan rendah (tanpa live music atau lagu bervolume tinggi)',
      'Jarak antar meja renggang untuk menjaga privasi membaca dan belajar',
      'Banyak sudut baca dengan pencahayaan hangat yang nyaman di mata',
      'Budaya saling menjaga ketenangan sesama pengunjung',
    ],
    idealFor: 'Membaca jurnal ilmiah, menyusun bab skripsi, dan belajar mandiri sebelum ujian.',
    spots: ['Babakan Heritage', 'Sempur Asri', 'Kawasan Bogor Selatan'],
  },
  {
    id: 'group-discussion',
    title: 'Group Discussion & Collab Hub',
    icon: Users,
    badge: 'Kerja Kelompok',
    badgeColor: 'bg-sky-50 text-sky-800 border-sky-300',
    tagline: 'Ruang komunal luas yang fleksibel untuk diskusi tugas kelompok dan proyek.',
    specs: [
      { label: 'Kapasitas Meja', level: 'Meja Komunal 6–8 Orang', status: 'optimal', desc: 'Cocok tim proyek PJBL' },
      { label: 'Toleransi Obrolan', level: 'Aktif Diperbolehkan', status: 'optimal', desc: 'Area semi-outdoor luas' },
      { label: 'Menu Sharing', level: 'Paket Hemat Pelajar', status: 'optimal', desc: 'Cemilan & minuman pitcher' },
      { label: 'Ketersediaan Daya', level: 'Stopkontak Sentral', status: 'good', desc: 'Tersedia di pilar meja' },
    ],
    features: [
      'Meja panjang komunal yang mampu menampung 4 hingga 8 mahasiswa',
      'Area semi-outdoor yang leluasa untuk bertukar ide dan presentasi',
      'Pilihan paket minuman dan cemilan hemat untuk sharing',
      'Fasilitas musholla dan area parkir motor luas',
    ],
    idealFor: 'Kerja kelompok PJBL, rapat panitia organisasi, dan brainstorming proyek.',
    spots: ['Jl. Pandu Raya', 'Tegal Gundil', 'Kawasan Air Mancur'],
  },
  {
    id: 'night-owl',
    title: 'Night Owl & Buka Larut Malam',
    icon: Moon,
    badge: 'Kejar Deadline',
    badgeColor: 'bg-indigo-50 text-indigo-800 border-indigo-300',
    tagline: 'Pilihan penyelamat saat butuh tempat nugas tengah malam hingga subuh.',
    specs: [
      { label: 'Jam Buka', level: 'Hingga 24.00 / 24 Jam', status: 'optimal', desc: 'Nonstop melayani begadang' },
      { label: 'Keamanan Lokasi', level: 'Parkir Dijaga Ketat', status: 'optimal', desc: 'Staf siaga sepanjang malam' },
      { label: 'Trafik Internet', level: 'Sangat Kencang Malam', status: 'optimal', desc: 'Bandwidth kosong & ngebut' },
      { label: 'Ketersediaan Daya', level: 'Aktif Sepanjang Malam', status: 'good', desc: 'Stopkontak siap pakai' },
    ],
    features: [
      'Jam operasional hingga pukul 24.00 atau buka 24 jam nonstop',
      'Staf dan barista siaga dengan keamanan parkir kendaraan yang aman',
      'Koneksi internet stabil saat malam hari dengan traffic lancar',
      'Pilihan kopi hangat dan makanan pengganjal perut untuk begadang',
    ],
    idealFor: 'Kejar deadline tugas tengah malam dan persiapan ujian esok pagi.',
    spots: ['Pajajaran Utara', 'Sukasari', 'Pusat Kota Bogor'],
  },
];

// ── Facility Tier Cards Data ──
export const FACILITY_TIERS = [
  {
    id: 'plug',
    name: 'Kepadatan Stopkontak / Colokan',
    icon: Zap,
    theme: 'amber',
    tag: 'Daya Laptop',
    tiers: [
      {
        title: 'Banyak Meja',
        pct: '45%',
        sub: '>70% meja ada colokan',
        desc: 'Tersedia stopkontak di setiap deret meja. Sangat aman untuk laptopan berjam-jam.',
        badge: 'Sangat Direkomendasikan',
        badgeClass: 'bg-emerald-100 text-emerald-900 border-emerald-300',
      },
      {
        title: 'Meja Tertentu',
        pct: '38%',
        sub: 'Dekat pilar / dinding / bar',
        desc: 'Stopkontak tersedia di meja tepi atau area kerja khusus. Sebaiknya datang lebih awal.',
        badge: 'Cukup Nyaman',
        badgeClass: 'bg-amber-100 text-amber-900 border-amber-300',
      },
      {
        title: 'Minim Colokan',
        pct: '17%',
        sub: '<30% meja / area outdoor',
        desc: 'Kerap diperuntukkan untuk nongkrong santai. Pastikan baterai laptop sudah penuh.',
        badge: 'Perlu Powerbank',
        badgeClass: 'bg-stone-100 text-stone-700 border-stone-300',
      },
    ],
    insight: '83% kafe di Kota Bogor yang terpetakan menyediakan stopkontak yang memadai bagi mahasiswa.',
  },
  {
    id: 'wifi',
    name: 'Kecepatan & Stabilitas Wi-Fi',
    icon: Wifi,
    theme: 'sky',
    tag: 'Konektivitas',
    tiers: [
      {
        title: 'Super Kencang (>50 Mbps)',
        pct: '52%',
        sub: 'Bandwidth dedicated fiber',
        desc: 'Sangat lancar untuk video call, download dataset SIG, hingga streaming perkuliahan daring.',
        badge: 'Optimal Riset & Zoom',
        badgeClass: 'bg-emerald-100 text-emerald-900 border-emerald-300',
      },
      {
        title: 'Stabil Menengah (20–50 Mbps)',
        pct: '36%',
        sub: 'Browsing & riset reguler',
        desc: 'Koneksi stabil untuk membuka Google Drive, Notion, dan mencari referensi e-book jurnal.',
        badge: 'Lancar Browsing',
        badgeClass: 'bg-sky-100 text-sky-900 border-sky-300',
      },
      {
        title: 'Kecepatan Dasar (<10 Mbps)',
        pct: '12%',
        sub: 'Akses pesan & dokumen ringan',
        desc: 'Cukup untuk kirim pesan WhatsApp dan chat, kurang cocok untuk download file berukuran besar.',
        badge: 'Kebutuhan Dasar',
        badgeClass: 'bg-stone-100 text-stone-700 border-stone-300',
      },
    ],
    insight: 'Mayoritas kafe di sepanjang koridor Pajajaran dan Bangbarung memiliki kecepatan di atas 30 Mbps.',
  },
  {
    id: 'quiet',
    name: 'Karakteristik Akustik & Suasana',
    icon: Volume2,
    theme: 'emerald',
    tag: 'Kenyamanan',
    tiers: [
      {
        title: 'Kondusif Belajar (50–65 dB)',
        pct: '48%',
        sub: 'Musik tenang & obrolan santai',
        desc: 'Suasana paling umum dengan musik latar instrumental. Nyaman untuk belajar maupun diskusi.',
        badge: 'Paling Seimbang',
        badgeClass: 'bg-teal-100 text-teal-900 border-teal-300',
      },
      {
        title: 'Zona Hening (35–45 dB)',
        pct: '34%',
        sub: 'Bebas live music & hening',
        desc: 'Tingkat suara sangat rendah. Sangat cocok bagi mahasiswa yang butuh konsentrasi tinggi.',
        badge: 'Khusus Skripsi',
        badgeClass: 'bg-emerald-100 text-emerald-900 border-emerald-300',
      },
      {
        title: 'Social Hub (>70 dB)',
        pct: '18%',
        sub: 'Suasana ramai / obrolan aktif',
        desc: 'Lebih condong ke tempat nongkrong komunal atau memiliki panggung pertunjukan musik.',
        badge: 'Kurang untuk Fokus',
        badgeClass: 'bg-stone-100 text-stone-700 border-stone-300',
      },
    ],
    insight: 'Filter suasana Go-around memudahkanmu menghindari kafe yang terlalu bising saat butuh ketenangan.',
  },
  {
    id: 'price',
    name: 'Transparansi Bujet Mahasiswa',
    icon: DollarSign,
    theme: 'violet',
    tag: 'Finansial',
    tiers: [
      {
        title: 'Hemat Pelajar (< Rp 20.000)',
        pct: '42%',
        sub: 'Kopi susu / teh / espresso',
        desc: 'Paling ramah di kantong mahasiswa untuk nugas harian tanpa membuat pengeluaran bengkak.',
        badge: 'Sangat Hemat',
        badgeClass: 'bg-emerald-100 text-emerald-900 border-emerald-300',
      },
      {
        title: 'Standar Menengah (Rp 20–35 rb)',
        pct: '46%',
        sub: 'Minuman kopi artisan / cemilan',
        desc: 'Rentang harga rata-rata kafe modern Kota Bogor dengan fasilitas ruang kerja yang lengkap.',
        badge: 'Harga Wajar',
        badgeClass: 'bg-violet-100 text-violet-900 border-violet-300',
      },
      {
        title: 'Spesialti Premium (> Rp 35.000)',
        pct: '12%',
        sub: 'Kopi biji impor / menu signature',
        desc: 'Pilihan untuk sesekali saat ingin menikmati cita rasa kopi spesialti atau suasana eksklusif.',
        badge: 'Premium Experience',
        badgeClass: 'bg-stone-100 text-stone-700 border-stone-300',
      },
    ],
    insight: 'Gunakan filter "Paling Hemat" di peta untuk langsung menyaring kafe di bawah Rp 20.000.',
  },
];

// ── Spatial Ranking Grid Data (Strictly 6 Kecamatan Kota Bogor) ──
export const DISTRICT_RANKINGS = [
  {
    id: 'tengah',
    rank: '#1',
    name: 'Bogor Tengah',
    cafes: '850+ Titik',
    pct: '29% dari total',
    densityTag: 'Kepadatan Tertinggi',
    tagClass: 'bg-emerald-100 text-emerald-900',
    transit: 'Biskita K1 & K2',
    campus: 'IPB Kampus Baranangsiang & Pascasarjana',
    desc: 'Episentrum utama ruang nugas Kota Bogor dengan pilihan kafe heritage hingga modern di sekitar SSA & Kebun Raya Bogor.',
    hotspots: ['Babakan', 'Sempur', 'Suryakencana', 'Paledang'],
  },
  {
    id: 'timur',
    rank: '#2',
    name: 'Bogor Timur',
    cafes: '620+ Titik',
    pct: '21% dari total',
    densityTag: 'Koridor Transit Utama',
    tagClass: 'bg-teal-100 text-teal-900',
    transit: 'Jalur Pajajaran & Tol Jagorawi',
    campus: 'Akses cepat IPB Baranangsiang & Pakuan',
    desc: 'Koridor coffee shop berkapasitas besar dengan area kerja luas, Wi-Fi kencang, dan jam buka panjang hingga malam.',
    hotspots: ['Jl. Pajajaran', 'Sukasari', 'Baranangsiang Indah', 'Katulampa'],
  },
  {
    id: 'utara',
    rank: '#3',
    name: 'Bogor Utara',
    cafes: '540+ Titik',
    pct: '19% dari total',
    densityTag: 'Hub Kampus Vokasi',
    tagClass: 'bg-sky-100 text-sky-900',
    transit: 'Biskita Koridor 2 & Cilibende',
    campus: 'Sekolah Vokasi IPB (Kampus Cilibende)',
    desc: 'Pusat tongkrongan dan nugas mahasiswa Vokasi IPB. Penuh kedai kopi ramah kantong mahasiswa.',
    hotspots: ['Cilibende', 'Bangbarung', 'Pandu Raya', 'Tegal Gundil'],
  },
  {
    id: 'barat',
    rank: '#4',
    name: 'Bogor Barat',
    cafes: '410+ Titik',
    pct: '14% dari total',
    densityTag: 'Koridor Yasmin & Bubulak',
    tagClass: 'bg-indigo-100 text-indigo-900',
    transit: 'Biskita Koridor 1 & Terminal Bubulak',
    campus: 'Simpul Transit Mahasiswa Barat Kota Bogor',
    desc: 'Kawasan barat Kota Bogor dengan suasana asri, kafe semi-outdoor yang sejuk di koridor Taman Yasmin hingga Cilendek.',
    hotspots: ['Taman Yasmin', 'Bubulak', 'Cilendek', 'Semplak'],
  },
  {
    id: 'sareal',
    rank: '#5',
    name: 'Tanah Sareal',
    cafes: '330+ Titik',
    pct: '11% dari total',
    densityTag: 'Zona Minimalis Modern',
    tagClass: 'bg-amber-100 text-amber-900',
    transit: 'Stasiun KRL Cilebut & Sholeh Iskandar',
    campus: 'Univ. Ibnu Khaldun (UIKA)',
    desc: 'Kawasan yang berkembang pesat dengan coffee shop minimalis modern yang tenang untuk belajar mandiri.',
    hotspots: ['Kebon Pedes', 'Jl. Sholeh Iskandar', 'Cimanggu'],
  },
  {
    id: 'selatan',
    rank: '#6',
    name: 'Bogor Selatan',
    cafes: '220+ Titik',
    pct: '8% dari total',
    densityTag: 'Zona Sejuk Alami',
    tagClass: 'bg-stone-200 text-stone-800',
    transit: 'Stasiun Batutulis & Koridor Cipaku',
    campus: 'Jalur sejuk Selatan Kota Bogor',
    desc: 'Menyuguhkan pemandangan alam dan udara sejuk yang sangat kondusif untuk membaca referensi tanpa bising kota.',
    hotspots: ['Batutulis', 'Cipaku', 'Empang', 'Bondongan'],
  },
];
