import type { RecommendationPlace } from './types';

export const MOCK_RECOMMENDATION_PLACES: RecommendationPlace[] = [
  {
    id: 1001,
    slug: 'maraca-books-and-coffee',
    name: 'Maraca Books and Coffee',
    address: 'Jl. Jalak Harupat No. 9A, Babakan, Bogor Tengah',
    subdistrict: 'Bogor Tengah',
    latitude: -6.59124,
    longitude: 106.79981,
    google_maps_url: 'https://www.google.com/maps/search/?api=1&query=-6.59124,106.79981',
    recommendation_score: 0,
    data_confidence: 94,
    distance_km: null,
    google_rating: 4.7,
    total_google_reviews: 1250,
    price_min_drink: 18_000,
    price_max_drink: 32_000,
    wifi_speed_mbps: 45,
    wifi_quality: 'fast',
    plug_availability: 'abundant',
    noise_level: 'quiet',
    amenities: ['plug', 'wifi', 'musholla', 'student_discount', 'air_conditioning'],
    image_url: 'https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=800&auto=format&fit=crop&q=80',
    is_open_now: true,
    last_verified_at: '2026-09-12T09:00:00+07:00',
    score_breakdown: {
      distance: null,
      rating: 92,
      price: 82,
      wifi: 78,
      plug: 100,
      quiet: 96,
    },
    reasons: [],
    warnings: [],
  },
  {
    id: 1002,
    slug: 'popolo-coffee-taman-kencana',
    name: 'Popolo Coffee Taman Kencana',
    address: 'Jl. Loader No. 9, Baranangsiang, Bogor Timur',
    subdistrict: 'Bogor Timur',
    latitude: -6.59835,
    longitude: 106.80812,
    google_maps_url: 'https://www.google.com/maps/search/?api=1&query=-6.59835,106.80812',
    recommendation_score: 0,
    data_confidence: 87,
    distance_km: null,
    google_rating: 4.65,
    total_google_reviews: 2340,
    price_min_drink: 24_000,
    price_max_drink: 42_000,
    wifi_speed_mbps: 60,
    wifi_quality: 'fast',
    plug_availability: 'moderate',
    noise_level: 'moderate',
    amenities: ['plug', 'wifi', 'air_conditioning', 'parking'],
    image_url: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&auto=format&fit=crop&q=80',
    is_open_now: true,
    last_verified_at: '2026-08-28T14:30:00+07:00',
    score_breakdown: {
      distance: null,
      rating: 91,
      price: 68,
      wifi: 86,
      plug: 70,
      quiet: 70,
    },
    reasons: [],
    warnings: [],
  },
  {
    id: 1003,
    slug: 'warkop-berkah-nusantara',
    name: 'Warkop Berkah Nusantara 24 Jam',
    address: 'Jl. Pajajaran Indah V No. 12, Baranangsiang, Bogor Timur',
    subdistrict: 'Bogor Timur',
    latitude: -6.60621,
    longitude: 106.81245,
    google_maps_url: 'https://www.google.com/maps/search/?api=1&query=-6.60621,106.81245',
    recommendation_score: 0,
    data_confidence: 81,
    distance_km: null,
    google_rating: 4.5,
    total_google_reviews: 620,
    price_min_drink: 6_000,
    price_max_drink: 15_000,
    wifi_speed_mbps: 35,
    wifi_quality: 'medium',
    plug_availability: 'abundant',
    noise_level: 'lively',
    amenities: ['plug', 'wifi', 'parking'],
    image_url: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&auto=format&fit=crop&q=80',
    is_open_now: true,
    last_verified_at: '2026-08-19T20:15:00+07:00',
    score_breakdown: {
      distance: null,
      rating: 86,
      price: 100,
      wifi: 68,
      plug: 100,
      quiet: 38,
    },
    reasons: [],
    warnings: [],
  },
  {
    id: 1004,
    slug: 'kedai-rindang-bogor',
    name: 'Kedai Rindang Bogor',
    address: 'Bogor Barat, Kota Bogor',
    subdistrict: 'Bogor Barat',
    latitude: -6.5753,
    longitude: 106.7706,
    google_maps_url: null,
    recommendation_score: 0,
    data_confidence: 48,
    distance_km: null,
    google_rating: 4.4,
    total_google_reviews: 87,
    price_min_drink: 15_000,
    price_max_drink: null,
    wifi_speed_mbps: null,
    wifi_quality: null,
    plug_availability: null,
    noise_level: 'quiet',
    amenities: ['musholla'],
    image_url: null,
    is_open_now: null,
    last_verified_at: null,
    score_breakdown: {
      distance: null,
      rating: 78,
      price: 88,
      wifi: null,
      plug: null,
      quiet: 92,
    },
    reasons: [],
    warnings: ['Informasi Wi-Fi dan colokan belum diverifikasi.'],
  },
  {
    id: 1005,
    slug: 'ruang-sore-pajajaran',
    name: 'Ruang Sore Pajajaran',
    address: 'Jl. Raya Pajajaran, Bogor Tengah',
    subdistrict: 'Bogor Tengah',
    latitude: -6.5898,
    longitude: 106.8061,
    google_maps_url: null,
    recommendation_score: 0,
    data_confidence: 61,
    distance_km: null,
    google_rating: null,
    total_google_reviews: null,
    price_min_drink: null,
    price_max_drink: null,
    wifi_speed_mbps: 22,
    wifi_quality: 'medium',
    plug_availability: 'limited',
    noise_level: null,
    amenities: ['wifi', 'air_conditioning'],
    image_url: null,
    is_open_now: false,
    last_verified_at: '2026-06-02T11:00:00+07:00',
    score_breakdown: {
      distance: null,
      rating: null,
      price: null,
      wifi: 58,
      plug: 35,
      quiet: null,
    },
    reasons: [],
    warnings: ['Harga, rating, dan tingkat kebisingan belum tersedia.'],
  },
];
